global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 10s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "sentry-server"

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    metric_relabel_configs:
      - source_labels: [container_label_com_docker_compose_project]
        regex: "self-hosted"
        action: keep

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-exporter:9113"]

  - job_name: "sentry-health"
    metrics_path: "/_health/"
    scheme: "http"
    scrape_interval: 15s
    scrape_timeout: 5s
    static_configs:
      - targets: ["host.docker.internal:9000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "sentry-web"
